### ISSUE TITLE
Rasa Web UI  in Flutter Mobile App

### ISSUE THREAD

**Issue by kjonnalagadda** [vivifyhealthcare/Rasabot#5]
**Rasa Web UI  in Flutter Mobile App**

This will provide feasibility to enable more functionalities with UI, which might be not available in third party UI interface.

Alternatively we have already released WEB UI Interface  in [main Branch](https://github.com/vivifyhealthcare/Rasabot)

**Comment by sacredabhishek** [comment]
[RASA Chatbot with Custom UI In Mobile App (Flutter) #38](https://github.com/orgs/vivifyhealthcare/discussions/38)
