### ISSUE TITLE
Boolean data (True/False) handling from API with intents

### ISSUE THREAD

**Issue by srujithapyla** [vivifyhealthcare/Rasabot#7]
**Is your feature request related to a problem? Please describe.**
To handle the boolean fields from the API and manage their response in BOT. In python api response boolean value is stored as 'true', and 'false' ; however in Rasa Bot boolean valuse is stored as 'True' and 'False'

**Describe the solution you'd like**
Created intents for handling boolean fields with 'true' and 'false'

**Comment by venkateshmalla777** [comment]
https://github.com/vivifyhealthcare/Rasabot/blob/7-boolean-data-truefalse-handling-from-api-with-intents/README.md****
